// Generated by scripts/gen-db-types.mjs — do not edit by hand.
//
// Regenerate after changing the schema:
//   node scripts/gen-db-types.mjs "postgresql://…" src/types/database.ts
//
// Use with @supabase/supabase-js:
//   createClient<Database>(SUPABASE_URL, SUPABASE_KEY)

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      activities: {
        Row: {
          id: string
          created_at: string
          client_id: string | null
          kind: string
          body: string | null
          due_at: string | null
          done: boolean
        }
        Insert: {
          id?: string
          created_at?: string
          client_id?: string | null
          kind?: string
          body?: string | null
          due_at?: string | null
          done?: boolean
        }
        Update: {
          id?: string
          created_at?: string
          client_id?: string | null
          kind?: string
          body?: string | null
          due_at?: string | null
          done?: boolean
        }
        Relationships: []
      }
      ad_metrics: {
        Row: {
          id: string
          customer_id: string
          account_name: string | null
          period_month: string
          period: string | null
          clicks: number | null
          impressions: number | null
          cost: number | null
          conversions: number | null
          ctr: number | null
          avg_cpc: number | null
          source: string | null
          updated_at: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          customer_id: string
          account_name?: string | null
          period_month: string
          period?: string | null
          clicks?: number | null
          impressions?: number | null
          cost?: number | null
          conversions?: number | null
          ctr?: number | null
          avg_cpc?: number | null
          source?: string | null
          updated_at?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          customer_id?: string
          account_name?: string | null
          period_month?: string
          period?: string | null
          clicks?: number | null
          impressions?: number | null
          cost?: number | null
          conversions?: number | null
          ctr?: number | null
          avg_cpc?: number | null
          source?: string | null
          updated_at?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      app_settings: {
        Row: {
          id: string
          data: Json | null
          updated_at: string | null
          created_at: string | null
        }
        Insert: {
          id: string
          data?: Json | null
          updated_at?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          data?: Json | null
          updated_at?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      assets: {
        Row: {
          id: string
          created_at: string
          client_id: string | null
          name: string
          kind: string
          url: string | null
          tags: string[]
          notes: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          client_id?: string | null
          name: string
          kind?: string
          url?: string | null
          tags?: string[]
          notes?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          client_id?: string | null
          name?: string
          kind?: string
          url?: string | null
          tags?: string[]
          notes?: string | null
        }
        Relationships: []
      }
      client_contacts: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          client_id: string
          name: string
          email: string
          phone: string | null
          title: string | null
          role: string
          is_primary: boolean
          portal_access: boolean
          auth_user_id: string | null
          notes: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          client_id: string
          name: string
          email: string
          phone?: string | null
          title?: string | null
          role?: string
          is_primary?: boolean
          portal_access?: boolean
          auth_user_id?: string | null
          notes?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          client_id?: string
          name?: string
          email?: string
          phone?: string | null
          title?: string | null
          role?: string
          is_primary?: boolean
          portal_access?: boolean
          auth_user_id?: string | null
          notes?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "client_contacts_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: true
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
        ]
      }
      clients: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          business_name: string
          contact_name: string | null
          email: string | null
          phone: string | null
          website: string | null
          city: string | null
          state: string | null
          category: string | null
          source: string | null
          stage: string
          priority: string
          rating: number | null
          services: string[]
          package_name: string | null
          mrr: number
          build_fee: number
          build_fee_paid: boolean
          start_date: string | null
          website_status: string
          build_url: string | null
          gbp_status: string
          gbp_url: string | null
          ads_status: string
          ads_budget: number | null
          domain_name: string | null
          domain_renews_on: string | null
          hosting_provider: string | null
          hosting_renews_on: string | null
          email_provider: string | null
          email_renews_on: string | null
          onboarding: Json
          next_follow_up: string | null
          follow_up_note: string | null
          notes: string | null
          welcome_status: string | null
          welcome_to: string | null
          welcome_sent_at: string | null
          welcome_error: string | null
          logo_url: string | null
          brand_color: string | null
          billing_mode: string | null
          recurring_addons: Json | null
          google_ads_id: string | null
          cole_pct: number | null
          build_review_status: string | null
          build_review_note: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          business_name: string
          contact_name?: string | null
          email?: string | null
          phone?: string | null
          website?: string | null
          city?: string | null
          state?: string | null
          category?: string | null
          source?: string | null
          stage?: string
          priority?: string
          rating?: number | null
          services?: string[]
          package_name?: string | null
          mrr?: number
          build_fee?: number
          build_fee_paid?: boolean
          start_date?: string | null
          website_status?: string
          build_url?: string | null
          gbp_status?: string
          gbp_url?: string | null
          ads_status?: string
          ads_budget?: number | null
          domain_name?: string | null
          domain_renews_on?: string | null
          hosting_provider?: string | null
          hosting_renews_on?: string | null
          email_provider?: string | null
          email_renews_on?: string | null
          onboarding?: Json
          next_follow_up?: string | null
          follow_up_note?: string | null
          notes?: string | null
          welcome_status?: string | null
          welcome_to?: string | null
          welcome_sent_at?: string | null
          welcome_error?: string | null
          logo_url?: string | null
          brand_color?: string | null
          billing_mode?: string | null
          recurring_addons?: Json | null
          google_ads_id?: string | null
          cole_pct?: number | null
          build_review_status?: string | null
          build_review_note?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          business_name?: string
          contact_name?: string | null
          email?: string | null
          phone?: string | null
          website?: string | null
          city?: string | null
          state?: string | null
          category?: string | null
          source?: string | null
          stage?: string
          priority?: string
          rating?: number | null
          services?: string[]
          package_name?: string | null
          mrr?: number
          build_fee?: number
          build_fee_paid?: boolean
          start_date?: string | null
          website_status?: string
          build_url?: string | null
          gbp_status?: string
          gbp_url?: string | null
          ads_status?: string
          ads_budget?: number | null
          domain_name?: string | null
          domain_renews_on?: string | null
          hosting_provider?: string | null
          hosting_renews_on?: string | null
          email_provider?: string | null
          email_renews_on?: string | null
          onboarding?: Json
          next_follow_up?: string | null
          follow_up_note?: string | null
          notes?: string | null
          welcome_status?: string | null
          welcome_to?: string | null
          welcome_sent_at?: string | null
          welcome_error?: string | null
          logo_url?: string | null
          brand_color?: string | null
          billing_mode?: string | null
          recurring_addons?: Json | null
          google_ads_id?: string | null
          cole_pct?: number | null
          build_review_status?: string | null
          build_review_note?: string | null
        }
        Relationships: []
      }
      content_items: {
        Row: {
          id: string
          created_at: string
          client_id: string | null
          title: string
          channel: string
          scheduled_for: string | null
          status: string
          body: string | null
          asset_url: string | null
          notes: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          client_id?: string | null
          title: string
          channel?: string
          scheduled_for?: string | null
          status?: string
          body?: string | null
          asset_url?: string | null
          notes?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          client_id?: string | null
          title?: string
          channel?: string
          scheduled_for?: string | null
          status?: string
          body?: string | null
          asset_url?: string | null
          notes?: string | null
        }
        Relationships: []
      }
      contractors: {
        Row: {
          id: string
          name: string
          split_pct: number
          active: boolean | null
          created_at: string | null
        }
        Insert: {
          id?: string
          name: string
          split_pct?: number
          active?: boolean | null
          created_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          split_pct?: number
          active?: boolean | null
          created_at?: string | null
        }
        Relationships: []
      }
      expenses: {
        Row: {
          id: string
          created_at: string | null
          expense_date: string | null
          client_id: string | null
          category: string | null
          vendor: string | null
          amount: number | null
          notes: string | null
          receipt_url: string | null
        }
        Insert: {
          id?: string
          created_at?: string | null
          expense_date?: string | null
          client_id?: string | null
          category?: string | null
          vendor?: string | null
          amount?: number | null
          notes?: string | null
          receipt_url?: string | null
        }
        Update: {
          id?: string
          created_at?: string | null
          expense_date?: string | null
          client_id?: string | null
          category?: string | null
          vendor?: string | null
          amount?: number | null
          notes?: string | null
          receipt_url?: string | null
        }
        Relationships: []
      }
      invoices: {
        Row: {
          id: string
          created_at: string
          client_id: string | null
          number: string | null
          description: string | null
          type: string
          amount: number
          status: string
          issued_on: string | null
          due_on: string | null
          paid_on: string | null
          method: string | null
          send_status: string | null
          sent_to: string | null
          sent_at: string | null
          send_error: string | null
          drive_status: string | null
          drive_url: string | null
          drive_saved_at: string | null
          drive_error: string | null
          items: Json | null
          rep: string | null
          rep_pct: number | null
          contact_name: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          client_id?: string | null
          number?: string | null
          description?: string | null
          type?: string
          amount?: number
          status?: string
          issued_on?: string | null
          due_on?: string | null
          paid_on?: string | null
          method?: string | null
          send_status?: string | null
          sent_to?: string | null
          sent_at?: string | null
          send_error?: string | null
          drive_status?: string | null
          drive_url?: string | null
          drive_saved_at?: string | null
          drive_error?: string | null
          items?: Json | null
          rep?: string | null
          rep_pct?: number | null
          contact_name?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          client_id?: string | null
          number?: string | null
          description?: string | null
          type?: string
          amount?: number
          status?: string
          issued_on?: string | null
          due_on?: string | null
          paid_on?: string | null
          method?: string | null
          send_status?: string | null
          sent_to?: string | null
          sent_at?: string | null
          send_error?: string | null
          drive_status?: string | null
          drive_url?: string | null
          drive_saved_at?: string | null
          drive_error?: string | null
          items?: Json | null
          rep?: string | null
          rep_pct?: number | null
          contact_name?: string | null
        }
        Relationships: []
      }
      meetings: {
        Row: {
          id: string
          created_at: string | null
          meeting_date: string | null
          meeting_time: string | null
          client_id: string | null
          title: string | null
          location: string | null
          attendees: string | null
          notes: string | null
          follow_up_on: string | null
        }
        Insert: {
          id?: string
          created_at?: string | null
          meeting_date?: string | null
          meeting_time?: string | null
          client_id?: string | null
          title?: string | null
          location?: string | null
          attendees?: string | null
          notes?: string | null
          follow_up_on?: string | null
        }
        Update: {
          id?: string
          created_at?: string | null
          meeting_date?: string | null
          meeting_time?: string | null
          client_id?: string | null
          title?: string | null
          location?: string | null
          attendees?: string | null
          notes?: string | null
          follow_up_on?: string | null
        }
        Relationships: []
      }
      onboarding_access_grants: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          engagement_id: string
          platform_key: string
          access_method: string
          status: string
          holder_contact_id: string | null
          holder_name: string | null
          holder_note: string | null
          verified_at: string | null
          verified_by_staff_id: string | null
          notes: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          engagement_id: string
          platform_key: string
          access_method?: string
          status?: string
          holder_contact_id?: string | null
          holder_name?: string | null
          holder_note?: string | null
          verified_at?: string | null
          verified_by_staff_id?: string | null
          notes?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          engagement_id?: string
          platform_key?: string
          access_method?: string
          status?: string
          holder_contact_id?: string | null
          holder_name?: string | null
          holder_note?: string | null
          verified_at?: string | null
          verified_by_staff_id?: string | null
          notes?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "onboarding_access_grants_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "onboarding_engagements"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_access_grants_holder_contact_id_fkey"
            columns: ["holder_contact_id"]
            isOneToOne: false
            referencedRelation: "client_contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_access_grants_platform_key_fkey"
            columns: ["platform_key"]
            isOneToOne: false
            referencedRelation: "onboarding_platforms"
            referencedColumns: ["key"]
          },
          {
            foreignKeyName: "onboarding_access_grants_verified_by_staff_id_fkey"
            columns: ["verified_by_staff_id"]
            isOneToOne: false
            referencedRelation: "staff_users"
            referencedColumns: ["id"]
          },
        ]
      }
      onboarding_assets: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          engagement_id: string
          engagement_section_id: string
          field_id: string | null
          row_id: string | null
          storage_bucket: string
          storage_path: string
          file_name: string
          mime_type: string | null
          byte_size: number | null
          kind: string
          caption: string | null
          uploaded_by_contact_id: string | null
          uploaded_by_staff_id: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          engagement_id?: string
          engagement_section_id: string
          field_id?: string | null
          row_id?: string | null
          storage_bucket?: string
          storage_path: string
          file_name: string
          mime_type?: string | null
          byte_size?: number | null
          kind?: string
          caption?: string | null
          uploaded_by_contact_id?: string | null
          uploaded_by_staff_id?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          engagement_id?: string
          engagement_section_id?: string
          field_id?: string | null
          row_id?: string | null
          storage_bucket?: string
          storage_path?: string
          file_name?: string
          mime_type?: string | null
          byte_size?: number | null
          kind?: string
          caption?: string | null
          uploaded_by_contact_id?: string | null
          uploaded_by_staff_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "onboarding_assets_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "onboarding_engagements"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_assets_engagement_section_id_fkey"
            columns: ["engagement_section_id"]
            isOneToOne: false
            referencedRelation: "onboarding_engagement_sections"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_assets_field_id_fkey"
            columns: ["field_id"]
            isOneToOne: false
            referencedRelation: "onboarding_fields"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_assets_row_id_fkey"
            columns: ["row_id"]
            isOneToOne: false
            referencedRelation: "onboarding_response_rows"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_assets_uploaded_by_contact_id_fkey"
            columns: ["uploaded_by_contact_id"]
            isOneToOne: false
            referencedRelation: "client_contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_assets_uploaded_by_staff_id_fkey"
            columns: ["uploaded_by_staff_id"]
            isOneToOne: false
            referencedRelation: "staff_users"
            referencedColumns: ["id"]
          },
        ]
      }
      onboarding_engagement_sections: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          engagement_id: string
          section_key: string
          assigned_contact_id: string | null
          due_date: string | null
          status: string
          position: number
          active: boolean
          started_at: string | null
          submitted_at: string | null
          accepted_at: string | null
          notes: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          engagement_id: string
          section_key: string
          assigned_contact_id?: string | null
          due_date?: string | null
          status?: string
          position?: number
          active?: boolean
          started_at?: string | null
          submitted_at?: string | null
          accepted_at?: string | null
          notes?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          engagement_id?: string
          section_key?: string
          assigned_contact_id?: string | null
          due_date?: string | null
          status?: string
          position?: number
          active?: boolean
          started_at?: string | null
          submitted_at?: string | null
          accepted_at?: string | null
          notes?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "onboarding_engagement_sections_assigned_contact_id_fkey"
            columns: ["assigned_contact_id"]
            isOneToOne: false
            referencedRelation: "client_contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_engagement_sections_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "onboarding_engagements"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_engagement_sections_section_key_fkey"
            columns: ["section_key"]
            isOneToOne: false
            referencedRelation: "onboarding_sections"
            referencedColumns: ["key"]
          },
        ]
      }
      onboarding_engagements: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          client_id: string
          template_key: string | null
          title: string | null
          vertical: string | null
          status: string
          due_date: string | null
          invited_at: string | null
          started_at: string | null
          submitted_at: string | null
          completed_at: string | null
          notes: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          client_id: string
          template_key?: string | null
          title?: string | null
          vertical?: string | null
          status?: string
          due_date?: string | null
          invited_at?: string | null
          started_at?: string | null
          submitted_at?: string | null
          completed_at?: string | null
          notes?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          client_id?: string
          template_key?: string | null
          title?: string | null
          vertical?: string | null
          status?: string
          due_date?: string | null
          invited_at?: string | null
          started_at?: string | null
          submitted_at?: string | null
          completed_at?: string | null
          notes?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "onboarding_engagements_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_engagements_template_key_fkey"
            columns: ["template_key"]
            isOneToOne: false
            referencedRelation: "onboarding_templates"
            referencedColumns: ["key"]
          },
        ]
      }
      onboarding_fields: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          section_key: string
          parent_field_id: string | null
          field_key: string
          label: string
          help_text: string | null
          placeholder: string | null
          field_kind: string
          field_type: string | null
          required: boolean
          position: number
          options: Json
          unit: string | null
          min_rows: number | null
          max_rows: number | null
          active: boolean
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          section_key: string
          parent_field_id?: string | null
          field_key: string
          label: string
          help_text?: string | null
          placeholder?: string | null
          field_kind?: string
          field_type?: string | null
          required?: boolean
          position?: number
          options?: Json
          unit?: string | null
          min_rows?: number | null
          max_rows?: number | null
          active?: boolean
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          section_key?: string
          parent_field_id?: string | null
          field_key?: string
          label?: string
          help_text?: string | null
          placeholder?: string | null
          field_kind?: string
          field_type?: string | null
          required?: boolean
          position?: number
          options?: Json
          unit?: string | null
          min_rows?: number | null
          max_rows?: number | null
          active?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "onboarding_fields_parent_field_id_fkey"
            columns: ["parent_field_id"]
            isOneToOne: false
            referencedRelation: "onboarding_fields"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_fields_section_key_fkey"
            columns: ["section_key"]
            isOneToOne: false
            referencedRelation: "onboarding_sections"
            referencedColumns: ["key"]
          },
        ]
      }
      onboarding_platform_triggers: {
        Row: {
          id: string
          created_at: string
          platform_key: string
          trigger_type: string
          trigger_key: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          platform_key: string
          trigger_type: string
          trigger_key?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          platform_key?: string
          trigger_type?: string
          trigger_key?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "onboarding_platform_triggers_platform_key_fkey"
            columns: ["platform_key"]
            isOneToOne: false
            referencedRelation: "onboarding_platforms"
            referencedColumns: ["key"]
          },
        ]
      }
      onboarding_platforms: {
        Row: {
          key: string
          created_at: string
          updated_at: string
          label: string
          category: string
          description: string | null
          position: number
          active: boolean
        }
        Insert: {
          key: string
          created_at?: string
          updated_at?: string
          label: string
          category?: string
          description?: string | null
          position?: number
          active?: boolean
        }
        Update: {
          key?: string
          created_at?: string
          updated_at?: string
          label?: string
          category?: string
          description?: string | null
          position?: number
          active?: boolean
        }
        Relationships: []
      }
      onboarding_response_rows: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          engagement_id: string
          engagement_section_id: string
          group_field_id: string
          position: number
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          engagement_id?: string
          engagement_section_id: string
          group_field_id: string
          position?: number
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          engagement_id?: string
          engagement_section_id?: string
          group_field_id?: string
          position?: number
        }
        Relationships: [
          {
            foreignKeyName: "onboarding_response_rows_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "onboarding_engagements"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_response_rows_engagement_section_id_fkey"
            columns: ["engagement_section_id"]
            isOneToOne: false
            referencedRelation: "onboarding_engagement_sections"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_response_rows_group_field_id_fkey"
            columns: ["group_field_id"]
            isOneToOne: false
            referencedRelation: "onboarding_fields"
            referencedColumns: ["id"]
          },
        ]
      }
      onboarding_responses: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          engagement_id: string
          engagement_section_id: string
          field_id: string
          row_id: string | null
          status: string
          value_text: string | null
          value_number: number | null
          value_boolean: boolean | null
          value_date: string | null
          value_json: Json | null
          answered_by_contact_id: string | null
          answered_by_staff_id: string | null
          answered_at: string
          updated_by_contact_id: string | null
          updated_by_staff_id: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          engagement_id?: string
          engagement_section_id: string
          field_id: string
          row_id?: string | null
          status?: string
          value_text?: string | null
          value_number?: number | null
          value_boolean?: boolean | null
          value_date?: string | null
          value_json?: Json | null
          answered_by_contact_id?: string | null
          answered_by_staff_id?: string | null
          answered_at?: string
          updated_by_contact_id?: string | null
          updated_by_staff_id?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          engagement_id?: string
          engagement_section_id?: string
          field_id?: string
          row_id?: string | null
          status?: string
          value_text?: string | null
          value_number?: number | null
          value_boolean?: boolean | null
          value_date?: string | null
          value_json?: Json | null
          answered_by_contact_id?: string | null
          answered_by_staff_id?: string | null
          answered_at?: string
          updated_by_contact_id?: string | null
          updated_by_staff_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "onboarding_responses_answered_by_contact_id_fkey"
            columns: ["answered_by_contact_id"]
            isOneToOne: false
            referencedRelation: "client_contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_responses_answered_by_staff_id_fkey"
            columns: ["answered_by_staff_id"]
            isOneToOne: false
            referencedRelation: "staff_users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_responses_engagement_id_fkey"
            columns: ["engagement_id"]
            isOneToOne: false
            referencedRelation: "onboarding_engagements"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_responses_engagement_section_id_fkey"
            columns: ["engagement_section_id"]
            isOneToOne: false
            referencedRelation: "onboarding_engagement_sections"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_responses_field_id_fkey"
            columns: ["field_id"]
            isOneToOne: false
            referencedRelation: "onboarding_fields"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_responses_row_id_fkey"
            columns: ["row_id"]
            isOneToOne: false
            referencedRelation: "onboarding_response_rows"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_responses_updated_by_contact_id_fkey"
            columns: ["updated_by_contact_id"]
            isOneToOne: false
            referencedRelation: "client_contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "onboarding_responses_updated_by_staff_id_fkey"
            columns: ["updated_by_staff_id"]
            isOneToOne: false
            referencedRelation: "staff_users"
            referencedColumns: ["id"]
          },
        ]
      }
      onboarding_sections: {
        Row: {
          key: string
          created_at: string
          updated_at: string
          title: string
          tier: string
          vertical: string | null
          intro: string | null
          description: string | null
          position: number
          active: boolean
        }
        Insert: {
          key: string
          created_at?: string
          updated_at?: string
          title: string
          tier: string
          vertical?: string | null
          intro?: string | null
          description?: string | null
          position?: number
          active?: boolean
        }
        Update: {
          key?: string
          created_at?: string
          updated_at?: string
          title?: string
          tier?: string
          vertical?: string | null
          intro?: string | null
          description?: string | null
          position?: number
          active?: boolean
        }
        Relationships: []
      }
      onboarding_template_sections: {
        Row: {
          template_key: string
          section_key: string
          position: number
        }
        Insert: {
          template_key: string
          section_key: string
          position?: number
        }
        Update: {
          template_key?: string
          section_key?: string
          position?: number
        }
        Relationships: [
          {
            foreignKeyName: "onboarding_template_sections_section_key_fkey"
            columns: ["section_key"]
            isOneToOne: false
            referencedRelation: "onboarding_sections"
            referencedColumns: ["key"]
          },
          {
            foreignKeyName: "onboarding_template_sections_template_key_fkey"
            columns: ["template_key"]
            isOneToOne: false
            referencedRelation: "onboarding_templates"
            referencedColumns: ["key"]
          },
        ]
      }
      onboarding_templates: {
        Row: {
          key: string
          created_at: string
          updated_at: string
          title: string
          description: string | null
          position: number
          active: boolean
        }
        Insert: {
          key: string
          created_at?: string
          updated_at?: string
          title: string
          description?: string | null
          position?: number
          active?: boolean
        }
        Update: {
          key?: string
          created_at?: string
          updated_at?: string
          title?: string
          description?: string | null
          position?: number
          active?: boolean
        }
        Relationships: []
      }
      payments: {
        Row: {
          id: string
          created_at: string
          client_id: string | null
          amount: number
          paid_on: string | null
          method: string | null
          kind: string
          note: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          client_id?: string | null
          amount?: number
          paid_on?: string | null
          method?: string | null
          kind?: string
          note?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          client_id?: string | null
          amount?: number
          paid_on?: string | null
          method?: string | null
          kind?: string
          note?: string | null
        }
        Relationships: []
      }
      proposals: {
        Row: {
          id: string
          created_at: string
          client_id: string | null
          title: string
          summary: string | null
          line_items: Json
          monthly_total: number
          build_total: number
          status: string
          sent_on: string | null
          contract_status: string
          contract_signed_on: string | null
          contract_url: string | null
          doc_type: string
          send_status: string | null
          sent_to: string | null
          sent_at: string | null
          send_error: string | null
          drive_status: string | null
          drive_url: string | null
          drive_saved_at: string | null
          drive_error: string | null
          details: Json
          approval_status: string | null
          approval_note: string | null
          approved_at: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          client_id?: string | null
          title: string
          summary?: string | null
          line_items?: Json
          monthly_total?: number
          build_total?: number
          status?: string
          sent_on?: string | null
          contract_status?: string
          contract_signed_on?: string | null
          contract_url?: string | null
          doc_type?: string
          send_status?: string | null
          sent_to?: string | null
          sent_at?: string | null
          send_error?: string | null
          drive_status?: string | null
          drive_url?: string | null
          drive_saved_at?: string | null
          drive_error?: string | null
          details?: Json
          approval_status?: string | null
          approval_note?: string | null
          approved_at?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          client_id?: string | null
          title?: string
          summary?: string | null
          line_items?: Json
          monthly_total?: number
          build_total?: number
          status?: string
          sent_on?: string | null
          contract_status?: string
          contract_signed_on?: string | null
          contract_url?: string | null
          doc_type?: string
          send_status?: string | null
          sent_to?: string | null
          sent_at?: string | null
          send_error?: string | null
          drive_status?: string | null
          drive_url?: string | null
          drive_saved_at?: string | null
          drive_error?: string | null
          details?: Json
          approval_status?: string | null
          approval_note?: string | null
          approved_at?: string | null
        }
        Relationships: []
      }
      reports: {
        Row: {
          id: string
          created_at: string
          client_id: string | null
          period: string | null
          period_start: string | null
          metrics: Json
          highlights: string | null
          notes: string | null
          next_steps: string | null
          send_status: string | null
          sent_to: string | null
          sent_at: string | null
          send_error: string | null
          drive_status: string | null
          drive_url: string | null
          drive_saved_at: string | null
          drive_error: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          client_id?: string | null
          period?: string | null
          period_start?: string | null
          metrics?: Json
          highlights?: string | null
          notes?: string | null
          next_steps?: string | null
          send_status?: string | null
          sent_to?: string | null
          sent_at?: string | null
          send_error?: string | null
          drive_status?: string | null
          drive_url?: string | null
          drive_saved_at?: string | null
          drive_error?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          client_id?: string | null
          period?: string | null
          period_start?: string | null
          metrics?: Json
          highlights?: string | null
          notes?: string | null
          next_steps?: string | null
          send_status?: string | null
          sent_to?: string | null
          sent_at?: string | null
          send_error?: string | null
          drive_status?: string | null
          drive_url?: string | null
          drive_saved_at?: string | null
          drive_error?: string | null
        }
        Relationships: []
      }
      reviews: {
        Row: {
          id: string
          created_at: string
          client_id: string | null
          customer_name: string | null
          channel: string
          status: string
          rating: number | null
          requested_on: string | null
          notes: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          client_id?: string | null
          customer_name?: string | null
          channel?: string
          status?: string
          rating?: number | null
          requested_on?: string | null
          notes?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          client_id?: string | null
          customer_name?: string | null
          channel?: string
          status?: string
          rating?: number | null
          requested_on?: string | null
          notes?: string | null
        }
        Relationships: []
      }
      staff_users: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          email: string
          name: string | null
          auth_user_id: string | null
          active: boolean
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          email: string
          name?: string | null
          auth_user_id?: string | null
          active?: boolean
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          email?: string
          name?: string | null
          auth_user_id?: string | null
          active?: boolean
        }
        Relationships: []
      }
      tasks: {
        Row: {
          id: string
          created_at: string
          client_id: string | null
          title: string
          detail: string | null
          assignee: string
          category: string
          status: string
          priority: string
          due_date: string | null
          recurring: boolean
          completed_at: string | null
          recur_interval: string
          due_time: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          client_id?: string | null
          title: string
          detail?: string | null
          assignee?: string
          category?: string
          status?: string
          priority?: string
          due_date?: string | null
          recurring?: boolean
          completed_at?: string | null
          recur_interval?: string
          due_time?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          client_id?: string | null
          title?: string
          detail?: string | null
          assignee?: string
          category?: string
          status?: string
          priority?: string
          due_date?: string | null
          recurring?: boolean
          completed_at?: string | null
          recur_interval?: string
          due_time?: string | null
        }
        Relationships: []
      }
      time_entries: {
        Row: {
          id: string
          created_at: string | null
          client_id: string | null
          task_id: string | null
          kind: string | null
          minutes: number | null
          entry_date: string | null
          notes: string | null
          started_at: string | null
        }
        Insert: {
          id?: string
          created_at?: string | null
          client_id?: string | null
          task_id?: string | null
          kind?: string | null
          minutes?: number | null
          entry_date?: string | null
          notes?: string | null
          started_at?: string | null
        }
        Update: {
          id?: string
          created_at?: string | null
          client_id?: string | null
          task_id?: string | null
          kind?: string | null
          minutes?: number | null
          entry_date?: string | null
          notes?: string | null
          started_at?: string | null
        }
        Relationships: []
      }
      trips: {
        Row: {
          id: string
          created_at: string | null
          trip_date: string | null
          client_id: string | null
          purpose: string | null
          miles: number | null
          rate: number | null
          notes: string | null
          from_address: string | null
          to_address: string | null
          round_trip: boolean | null
        }
        Insert: {
          id?: string
          created_at?: string | null
          trip_date?: string | null
          client_id?: string | null
          purpose?: string | null
          miles?: number | null
          rate?: number | null
          notes?: string | null
          from_address?: string | null
          to_address?: string | null
          round_trip?: boolean | null
        }
        Update: {
          id?: string
          created_at?: string | null
          trip_date?: string | null
          client_id?: string | null
          purpose?: string | null
          miles?: number | null
          rate?: number | null
          notes?: string | null
          from_address?: string | null
          to_address?: string | null
          round_trip?: boolean | null
        }
        Relationships: []
      }
    };
    Views: {
      onboarding_engagement_platforms: {
        Row: {
          engagement_id: string | null
          platform_key: string | null
          label: string | null
          category: string | null
          description: string | null
          position: number | null
        }
        Relationships: []
      }
      onboarding_my_client: {
        Row: {
          id: string | null
          business_name: string | null
          city: string | null
          state: string | null
          website: string | null
          logo_url: string | null
          brand_color: string | null
        }
        Relationships: []
      }
      onboarding_section_progress: {
        Row: {
          engagement_section_id: string | null
          engagement_id: string | null
          section_key: string | null
          status: string | null
          assigned_contact_id: string | null
          due_date: string | null
          field_count: number | null
          response_count: number | null
          answered_count: number | null
          unknown_count: number | null
          not_applicable_count: number | null
          percent_complete: number | null
        }
        Relationships: []
      }
    };
    Functions: {
      bind_auth_identity: {
        Args: Record<PropertyKey, never>
        Returns: undefined
      }
      current_auth_email: {
        Args: Record<PropertyKey, never>
        Returns: string
      }
      is_staff: {
        Args: Record<PropertyKey, never>
        Returns: boolean
      }
      looks_like_secret: {
        Args: {
          t: string
        }
        Returns: boolean
      }
      onboarding_client_ids: {
        Args: Record<PropertyKey, never>
        Returns: string[]
      }
      onboarding_engagement_ids: {
        Args: Record<PropertyKey, never>
        Returns: string[]
      }
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type PublicSchema = Database['public'];

export type Tables<T extends keyof (PublicSchema['Tables'] & PublicSchema['Views'])> =
  (PublicSchema['Tables'] & PublicSchema['Views'])[T] extends { Row: infer R } ? R : never;

export type TablesInsert<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T] extends { Insert: infer I } ? I : never;

export type TablesUpdate<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T] extends { Update: infer U } ? U : never;

// ---- Onboarding vocabularies ------------------------------------------------
// These live as text + CHECK constraints rather than Postgres enums, matching
// how every other status column in this database is modelled, so they are
// restated here as string unions for the editor's benefit.

export type SectionTier = 'core' | 'scope' | 'advisory' | 'vertical';

export type FieldKind = 'scalar' | 'repeating_group';

export type FieldType =
  | 'short_text' | 'long_text' | 'number' | 'currency' | 'date' | 'email'
  | 'phone' | 'url' | 'boolean' | 'select' | 'multi_select' | 'file_upload'
  | 'checklist_item';

/** `unknown` and `not_applicable` are deliberate answers, not blanks. */
export type ResponseStatus = 'answered' | 'unknown' | 'not_applicable';

export type EngagementStatus =
  | 'draft' | 'invited' | 'in_progress' | 'submitted' | 'complete' | 'archived';

export type EngagementSectionStatus =
  | 'not_started' | 'in_progress' | 'submitted' | 'accepted' | 'waived';

/** How TaylorMade holds access. Never a credential — see onboarding_access_grants. */
export type AccessMethod = 'delegated' | 'shared' | 'owner_holds' | 'unknown' | 'missing';

export type AccessStatus =
  | 'pending' | 'requested' | 'granted' | 'verified' | 'blocked' | 'not_applicable';

export type ContactRole = 'owner' | 'operations' | 'finance' | 'marketing' | 'contact';

export type FieldOption = { value: string; label: string };
